### ISSUE TITLE
Based on the FMEA min degraded mode should only be triggered for flow or pressure sensor not working

### ISSUE THREAD

**Issue by BranimirMrak** [beademingstoestel/arduino_pid_code#10]
Current implementation
min_degraded_mode_ON = checkDegradedMode(isFlow2PatientRead, isPatientPressureCorrect, isAmbientPressureCorrect, battery_above_25, temperature_OK, fan_OK);

Desired 
min_degraded_mode_ON = checkDegradedMode (isFlow2PatientRead, isPatientPressureCorrect);

**Comment by ThomasVDD** [comment]
Fixed in V2.28
