### ISSUE TITLE
alarm stays muted on Arduino if GUI PC is disconnected

### ISSUE THREAD

**Issue by BranimirMrak** [beademingstoestel/arduino_pid_code#12]

**Comment by ThomasVDD** [comment]
Fixed in V2.49

**Comment by BranimirMrak** [comment]
Performed tests on v 3.05 (System logs report **3.5**): 

- mute alarm in GUI
- disconnect PC from Arduino
- GUI reports visual alarm (no Arduino) but does not beep, machine does not alarm at all (beep or light)
- when re-connecting USB machine beeps and GUI shows "no GUI" :-D
