### ISSUE TITLE
switch to min degraded mode from one time sample to the next leads to jumping pressure reference

### ISSUE THREAD

**Issue by BranimirMrak** [beademingstoestel/arduino_pid_code#13]
min_degraded_mode_ON should only be allowed to evaluate in the state machine. So that we cannot toggle between normal operation mode and min degraded state

alternatively, if the idea above is not implementable, arduino should stay in min degraded state for good, once it enters it. Only a full reset starts the machine in normal mode. This would be similar to how the reset is done for the other errors. Makes sense ?

**Comment by ThomasVDD** [comment]
Seems to be fixed by communication fix
