### ISSUE TITLE
take 2: alarm stays muted on Arduino if GUI PC is disconnected

### ISSUE THREAD

**Issue by BranimirMrak** [beademingstoestel/arduino_pid_code#14]
Performed tests on v 3.05 (System logs report **3.5**): 

- mute alarm in GUI
- disconnect PC from Arduino
- GUI reports visual alarm (no Arduino) but does not beep, machine does not alarm at all (beep or light)
- when re-connecting USB machine beeps and GUI shows "no GUI" :-D

_Originally posted by @Mrak90 in https://github.com/beademingstoestel/arduino_pid_code/issues/12#issuecomment-614706127_

**Comment by ThomasVDD** [comment]
Fixed in V3.08
