### ISSUE TITLE
Dodgy battery SoC

### ISSUE THREAD

**Issue by BranimirMrak** [beademingstoestel/arduino_pid_code#17]
not a bug, but the current implementation looks dodgy. Should be tested!

**Comment by ThomasVDD** [comment]
Fixed in V3.26

**Comment by BranimirMrak** [comment]
Was this tested vs. battery voltage ?

**Comment by ThomasVDD** [comment]
Taken from discharge curves of lead acid batteries

**Comment by ThomasVDD** [comment]
Still to be tested though!
