### ISSUE TITLE
Wathdog message from Atmega processo to python not yet implemented

### ISSUE THREAD

**Issue by HenkVandecasteele** [beademingstoestel/arduino_pid_code#2]
For Python-engine to have some certainty the atmega chip is running all of his tasks, a Watchdog message from the Atmega chip should be sent to the Python engine. Inside should be the counter that was received last time. from the Python Engine. Sending this message python should be the last step in the 10ms task. In case the 10ms stops running before that moment, the Python engine will notice.

**Comment by ThomasVDD** [comment]
Changed in V2
