### ISSUE TITLE
MUTE setting has no effect

### ISSUE THREAD

**Issue by TomBruyneel** [beademingstoestel/arduino_pid_code#5]
When clicking the mute button in the GUI the alarm keeps sounding v2.07

**Comment by TomBruyneel** [comment]
Setting received correctly and saved correctly on arduino, but not used

**Comment by TomBruyneel** [comment]
It seems it does have an effect, but only after starting and stopping again

**Comment by ThomasVDD** [comment]
Fixed in V2.30!
